all:
  children:
    # Amazon Linux Group
    amazon_linux:
      hosts:
        amazon_linux_1:
          ansible_host: ansible-amazon-linux-1.shopback.engineering
          ansible_ssh_private_key_file: "{{ key_path }}"
          ansible_user: ec2-user
        amazon_linux_2:
          ansible_host: ansible-amazon-linux-2.shopback.engineering
          ansible_ssh_private_key_file: "{{ key_path }}"
          ansible_user: ec2-user

    # Ubuntu Group
    ubuntu:
      hosts:
        ubuntu_1:
          ansible_host: ansible-ubuntu-1.shopback.engineering
          ansible_ssh_private_key_file: "{{ key_path }}"
          ansible_user: ubuntu
        ubuntu_2:
          ansible_host: ansible-ubuntu-2.shopback.engineering
          ansible_ssh_private_key_file: "{{ key_path }}"
          ansible_user: ubuntu
