amazon_linux:
  hosts:
    ansible-amazon-linux-1.shopback.engineering:
    ansible-amazon-linux-2.shopback.engineering:

ubuntu:
  hosts:
    ansible-ubuntu-1.shopback.engineering:
    ansible-ubuntu-2.shopback.engineering:
