# Source: labs/playbook.yml

# Play
- name: Ensure .gitconfig copied from master.gitconfig
  hosts: localhost

  tasks:
    # Task
    - name: Create a root directory if it does not exist
      file: path=/tmp/learning-ansible state=directory mode=0755

      # Run Handler
      notify: restart a service

    # Task
    - copy:
        src: master.gitconfig
        dest: /tmp/learning-ansible/.gitconfig

  handlers:
    - name: restart a service
      debug: msg="Your service has been restarted"
