# Source: labs/playbook.yml

- name: Ensure .gitconfig copied from master.gitconfig
  hosts: localhost

  tasks:
    - name: Create a root directory if it does not exist
      file: path=/tmp/learning-ansible state=directory mode=0755
      notify: restart a service

    - copy:
        src: master.gitconfig
        dest: /tmp/learning-ansible/.gitconfig

  handlers:
    - name: restart a service
      debug: msg="Your service has been restarted"
